# Base image
FROM python:3.6.5-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy pip requirements to WORKDIR
COPY ./requirements.txt /usr/src/app/requirements.txt

# Install requirements
RUN pip install -r requirements.txt

# Add app source code
COPY . /usr/src/app

# Run server
CMD python manage.py run -h 0.0.0.0
