# Base image
FROM python:3.6.5-alpine

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
RUN apk update && apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && apk add netcat-openbsd

# Copy pip requirements to WORKDIR
COPY ./requirements.txt /usr/src/app/requirements.txt

# Install requirements
RUN pip install -r requirements.txt

# Add entrypoint script
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Add app source code
COPY . /usr/src/app

# Run server
CMD ["/usr/src/app/entrypoint.sh"]
